# Generated by Django 5.1.1 on 2024-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('medida', models.CharField(max_length=20)),
                ('caducidad', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('stado', models.CharField(default='activo', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=255)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ubicacion', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
